grpc_server:
  address: ":8081"
  timeout: "2s"
mongo_db:
  url: "mongodb://root:example@localhost:27017/db_sso"
  db_name: db_sso
  username: root
  password: example
jwt:
  issuer: auth-service
  access_expires_in: 10h
  refresh_expires_in: 30h
  public_key: ./public_key.pem   
  private_key: ./private_key.pem